name: PHPUnit

on: [ push, pull_request ]

jobs:
  ci:
    name: Test PHP ${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          extensions: redis, pdo, pdo_mysql, bcmath, swoole
          ini-values: opcache.enable_cli=1
          coverage: none
      - name: Setup Services
        run: |
          docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --name elasticsearch elasticsearch:5-alpine
          docker run -d -p 19200:9200 -p 19300:9300 -e "discovery.type=single-node" --name elasticsearch elasticsearch:7-alpine
          sleep 5
      - name: Setup Packages
        run: composer update -o --no-scripts
      - name: Run Scripts before Test
        run: php tests/setup_elasticsearch.php
      - name: Run Test Cases
        run: |
          composer analyse
          composer test
